name: hekinav
description: Advanced public transport routing tool

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
    
  mapbox_maps_flutter: ^2.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  graphql: ^5.2.0-beta.9
  polyline_codec: ^0.1.6
  path_provider: ^2.1.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - auth/secrets.json
    - assets/images/pin_red.png
    - assets/images/pin_green.png
